# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:    
    - task: UseDotNet@2
      displayName: 'Use .NET 2 Core sdk'
      inputs:
        packageType: sdk
        version: 2.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - bash: |
        pwd
        ls
      displayName: list folders
    
    - script: dotnet restore falcon_worker.sln --configfile nuget/NuGet.Config
      displayName: Restore Dependencies
    